In [1]:
import numpy as np
A = np.array([1,2,3,4])

In [2]:
print(A)

[1 2 3 4]


In [4]:
np.ndim(A)

1

In [5]:
A.shape

(4,)

In [8]:
A.shape[0]

4

------------

In [9]:
B = np.array([[1,2,3],[4,5,6]])

In [10]:
print(B)

[[1 2 3]
 [4 5 6]]


In [11]:
np.ndim(B)

2

In [12]:
B.shape

(2, 3)

---------

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

In [14]:
print(A.shape, B.shape)

(2, 2) (2, 2)


In [15]:
A*B

array([[4, 6],
       [6, 4]])

In [16]:
np.dot(A,B)

array([[ 8,  5],
       [20, 13]])

-----------

In [17]:
X = np.array([1,2])
W = np.array([[2,3,4],[3,4,5]])

In [18]:
Y = np.dot(X,W)

In [19]:
Y

array([ 8, 11, 14])

In [20]:
Y.shape

(3,)